import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../src/components/Header";
import MainPage from "../src/components/MainPage";
import Footer from "../src/components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AmplioNow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainPage />
      <Footer />
    </div>
  );
}
