import React, { useEffect, useState } from "react";
import Head from "next/head";
import Lottie from "react-lottie";
import Image from "next/image";
import loadingIcon from "../src/images/loadingIcon.json";
import styles from "../styles/Home.module.css";
import Header from "../src/components/Header";
import MainPage from "../src/components/MainPage";
import Footer from "../src/components/Footer";

export default function Home() {
  const [loading, setLoading] = useState(true);

  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: loadingIcon,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, [1000]);
  }, []);

  if (loading) {
    return (
      <div className={styles.loadingContainer}>
        <Lottie options={defaultOptions} height={"15%"} width={"15%"} />
      </div>
    );
  } else {
    return (
      <div className={styles.container}>
        {/* <a href="https://www.freepik.com/vectors/phone-3d">
          Phone 3d vector created by pikisuperstar - www.freepik.com
        </a>
        <a href="https://www.freepik.com/vectors/social-background">
          Social background vector created by pikisuperstar - www.freepik.com
        </a>
        <a href="https://www.freepik.com/vectors/phone-3d">
          Phone 3d vector created by pikisuperstar - www.freepik.com
        </a> */}
        <Head>
          <title>AmplioNow</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/IconAmplioNow.png" />
        </Head>
        <Header />
        <MainPage />
        <Footer />
      </div>
    );
  }
}
